import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Toaster } from '~/components/ui/sonner'
import Header from '~/components/layout/Header'
import Footer from '~/components/layout/Footer'
import Providers from '~/components/Providers'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <div className="relative flex h-screen flex-col">
            <Header />
            <Toaster
              position="top-center"
              className="h-[65px] text-base"
            />
            {children}
            <Footer />
          </div>
        </Providers>
      </body>
    </html>
  )
}
