import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Toaster } from '~/components/ui/sonner'
import Header from '~/components/layout/Header'
import Footer from '~/components/layout/Footer'
import Providers from '~/components/Providers'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <div className="relative flex h-screen flex-col">
            <Header />
            <Toaster
              position="top-center"
              toastOptions={{
                className: 'h-[65px] text-base pl-8 md:min-w-[450px]',
                classNames: {
                  closeButton:
                    'right-0 left-auto top-1/2 -translate-x-[50%] -translate-y-[50%] !text-black mr-8 !w-6 !h-6'
                }
              }}
            />
            {children}
            <Footer />
          </div>
        </Providers>
      </body>
    </html>
  )
}
